# -*- coding: utf-8 -*-
"""Assignment #1 (C)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19PZ3SZsDz0kZc1mTxbdz9EMw8TMkTSiW
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from IPython.display import Image

from google.colab import drive
drive.mount('/content/gdrive')

path = "/content/gdrive/MyDrive/DLIVACV_workshop/Assignment/Assignment_1/"

def displayImage(image):
    if len(image.shape)==3:
        color_coverted = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        plt.imshow(color_coverted)
        plt.show()
        
    else:
        plt.imshow(image, cmap="gray")
        plt.show()

img = cv2.imread(path+'coin.jpeg')
grayImage =cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

displayImage(grayImage)

blurImage=cv2.GaussianBlur(grayImage,(7,7),5)
displayImage(blurImage)

cannyImage = cv2.Canny(blurImage,25,210)
displayImage(cannyImage)

(cnt,heirarchy)=cv2.findContours(cannyImage.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
rgb=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.drawContours(rgb, cnt, -1, (0,255,0),2)

plt.imshow(rgb)

print ('Coins in the image: ', len(cnt))